# Generated by Django 5.0.1 on 2026-02-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
