# Generated by Django 5.0.1 on 2026-02-06 10:36

from django.db import migrations

def make_admin_user(apps, schema_editor):
    User = apps.get_model("auth", "User")
    try:
        user = User.objects.get(username="root")
        user.is_staff = True
        user.is_superuser = True
        user.save()
    except User.DoesNotExist:
        pass  # no-op if user not created yet


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_budget'),
    ]

    operations = [
        migrations.RunPython(make_admin_user, migrations.RunPython.noop),
    ]
