# Generated by Django 5.0.1 on 2026-02-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_make_admin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_income',
            field=models.BooleanField(default=False),
        ),
    ]
