# Generated by Django 5.0.1 on 2026-02-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_transaction_is_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='file_type',
            field=models.CharField(choices=[('csv', 'CSV'), ('pdf', 'PDF'), ('xlsx', 'XLSX'), ('xls', 'XLS')], max_length=10),
        ),
    ]
